### ISSUE TITLE
Mojilala API stopped working

### ISSUE THREAD

**Issue by ghost** [mojilala/sticker-api#1]
Hi,

Mojilala API stopped working a couple of days ago. It throws an SSL exception (you can check it if you try to visit https://api.mojilala.com from Chrome).

Is this API discontinued or are you working on a fix for this?

Best

**Comment by adamdilek** [comment]
@francesctt thx for reporting. We are fixing it.

**Comment by adamdilek** [comment]
@francesctt it has fixed, can you check ?

**Comment by ghost** [comment]
@muhammet It's fixed, thanks!
